# Generated by Django 6.0.7 on 2026-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting in Queue'), ('Serving', 'Currently Serving'), ('Completed', 'Completed'), ('Missed', 'Missed/No-Show')], default='Waiting', max_length=20),
        ),
    ]
