# Generated by Django 6.0.7 on 2026-08-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text="Set when the ticket's QR code is scanned/verified at the front desk.", null=True),
        ),
    ]
