# Generated by Django 6.0.7 on 2026-08-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_checked_in_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Set when the appointment is marked Completed or Missed. Used to measure transaction duration.', null=True),
        ),
    ]
