# Generated by Django 6.0.7 on 2026-08-03 15:13

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('queue_number'), name='unique_queue_number_per_day'),
        ),
    ]
